# Generated by Django 2.0.7 on 2018-07-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacter',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
